# Generated by Django 2.2.4 on 2019-11-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
