# Generated by Django 2.2.4 on 2019-11-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_placeholder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeholder',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='placeholder',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
