# Generated by Django 2.2.4 on 2019-11-04 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20191104_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
