# Generated by Django 2.2.4 on 2019-11-04 07:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_placeholder_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
